#!/bin/sh
# Creates .env from .env.example with random secrets, and the object store's identity file with the same S3 keys
# (TDD-0005 H7). Run once on a new machine, before the first `docker compose up`. Refuses to touch an existing .env:
# several secrets are fixed at the first start (ZITADEL_MASTERKEY encrypts data inside the identity provider).
#   cd infrastructure/compose && sh init-env.sh
set -eu
cd "$(dirname "$0")"

if [ -e .env ]; then
  echo ".env already exists: not overwritten (rotating these secrets is not just a file edit)" >&2
  exit 1
fi

# n random bytes as 2n lower-case hex characters.
hex() { od -An -tx1 -N "$1" /dev/urandom | tr -d ' \n'; }

postgres_password=$(hex 24)
zitadel_db_password=$(hex 24)
masterkey=$(hex 16) # exactly 32 characters
admin_password="Aa1!$(hex 12)" # the IdP's default policy wants upper, lower, digit and symbol
s3_access_key="averyn-$(hex 8)"
s3_secret_key=$(hex 24)

umask 077
sed \
  -e "s/^POSTGRES_PASSWORD=.*/POSTGRES_PASSWORD=${postgres_password}/" \
  -e "s/^ZITADEL_MASTERKEY=.*/ZITADEL_MASTERKEY=${masterkey}/" \
  -e "s/^ZITADEL_DB_PASSWORD=.*/ZITADEL_DB_PASSWORD=${zitadel_db_password}/" \
  -e "s/^ZITADEL_ADMIN_PASSWORD=.*/ZITADEL_ADMIN_PASSWORD=${admin_password}/" \
  .env.example > .env.tmp
cat >> .env.tmp <<EOF

# Generated by init-env.sh: the backend's object-store keys, also in seaweedfs-s3.local.json.
S3_ACCESS_KEY=${s3_access_key}
S3_SECRET_KEY=${s3_secret_key}
S3_CONFIG_FILE=./seaweedfs-s3.local.json
EOF
cat > seaweedfs-s3.local.json <<EOF
{
  "identities": [
    {
      "name": "averyn",
      "credentials": [{ "accessKey": "${s3_access_key}", "secretKey": "${s3_secret_key}" }],
      "actions": ["Admin", "Read", "Write", "List", "Tagging"]
    }
  ]
}
EOF
if grep -v '^#' .env.tmp | grep -q 'CHANGE'; then
  rm -f .env.tmp seaweedfs-s3.local.json
  echo "a CHANGE placeholder in .env.example was not replaced: update init-env.sh" >&2
  exit 1
fi
mv .env.tmp .env
# The object store reads this file as its own (non-root, unknown) user through a bind mount: it must be world-readable.
chmod 644 seaweedfs-s3.local.json
echo "wrote .env and seaweedfs-s3.local.json; the IdP console admin password is ZITADEL_ADMIN_PASSWORD in .env"
